// static meta data
export const metadata = {
    title: "ArbazAnsari About Page",
    description: "this about page is generated by arbaz ansari",
};

import React from 'react'

const AboutPage = () => {
    return (
        <div>AboutPage</div>
    )
}

export default AboutPage